#!perl

# DATE
# DIST
# VERSION

use strict;
use warnings;

use Term::Size;

my ($columns, $rows) = Term::Size::chars *STDOUT{IO};
print "$columns x $rows\n";

# PODNAME:
# ABSTRACT: Print terminal size according to Term::Size

=head1 SYNOPSIS

 % term-size


=head1 SEE ALSO

L<Term::Size>
