#!perl

use strict;
use warnings;
use Term::Detect::Software qw(detect_terminal);
use Data::Dump;

dd detect_terminal();

# PODNAME:
# ABSTRACT: Detect terminal software using Term::Detect::Software

=head1 SYNOPSIS

 % term-detect-software

Sample result:

 {
   _debug_info     => ["detect: konsole via KONSOLE_DBUS_{SERVICE,SESSION} env"],
   box_chars       => 1,
   color_depth     => 16777216,
   default_bgcolor => "000000",
   emulator_engine => "konsole",
   unicode         => 1,
 }


=head1 DESCRIPTION

This is a simple CLI for L<Term::Detect::Software>.


=head1 SEE ALSO

L<Term::Detect::Software>
