#!perl

# DATE
# VERSION

use strict;
use warnings;

package
    MyApp;
use Moo;
with 'Term::App::Role::Attrs';
use Data::Dump;

sub run {
    my $self = shift;

    dd {
        use_utf8      => $self->use_utf8,
        use_box_chars => $self->use_box_chars,
        interactive   => $self->interactive,
        use_color     => $self->use_color,
        color_depth   => $self->color_depth,
        term_width    => $self->term_width,
        term_height   => $self->term_height,
        _term_attrs_debug_info => $self->_term_attrs_debug_info,
    };
}

package
    main;
MyApp->new->run;

# ABSTRACT: Show terminal attributes (from Term::App::Role::Attrs)
# PODNAME:

=head1 SYNOPSIS

 % term-attrs

Sample result:

 {
   _term_attrs_debug_info => {
                               color_depth_from   => "detect_terminal",
                               interactive_from   => "-t STDOUT",
                               term_height_from   => "term_size",
                               term_width_from    => "term_size",
                               use_box_chars_from => "detect_terminal",
                               use_color_from     => "interactive + color_deth",
                               use_utf8_from      => "detect_terminal + LANG/LANGUAGE env must include \"utf8\"",
                             },
   color_depth            => 16777216,
   interactive            => 1,
   term_height            => 45,
   term_width             => 192,
   use_box_chars          => 1,
   use_color              => 1,
   use_utf8               => 1,
 }


=head1 DESCRIPTION

This is a simple CLI for L<Term::App::Role::Attrs>. It shows what values are
provided for applications that use that role.


=head1 SEE ALSO

L<Term::App::Role::Attrs>
